SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

KILL_BORDER_LEFT = 0 - (ASTEROID_MAX_RADIUS * 2)
KILL_BORDER_BOTTOM = 0 - (ASTEROID_MAX_RADIUS * 2)
KILL_BORDER_RIGHT = SCREEN_WIDTH + (ASTEROID_MAX_RADIUS * 2)
KILL_BORDER_TOP = SCREEN_HEIGHT + (ASTEROID_MAX_RADIUS * 2)

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 225
PLAYER_SPEED = 175

SHOT_SPEED = 500
SHOT_RADIUS = 5
SHOT_COOLDOWN = 0.30